version: "3.9"

services:
  gentle:
    image: gentle/standard:latest
    container_name: gentle
    ports:
      - "8765:8765"

  text-to-video:
    build: .
    container_name: text-to-video
    ports:
      - "8000:80"
    depends_on:
      - gentle